[project]
name = "nyaya"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[all]>=0.119.0",
    "pinecone>=7.3.0",
    "python-dotenv>=1.1.1",
]
